In [19]:
import pandas as pd

In [20]:
# =====================================================
# Load Dataset & Basic Preprocessing
# =====================================================

df = pd.read_csv("../Raw Data/customers.csv")
df['signup_date'] = pd.to_datetime(df['signup_date'])
df.head()

,customer_id,customer_name,email,phone,gender,signup_date,city,state,pincode
0,CUST000001,Ravi Chandel,ravi.chandel293@outlook.com,7.073180e+09,Male,2025-01-12,Mumbai,Maharashtra,391618.0
1,CUST000002,Komal Chakraborty,komal.chakraborty606@gmail.com,6.015525e+09,Female,2025-02-15,Ahmedabad,Gujarat,223628.0
2,CUST000003,Garima Negi,garima.negi681@yahoo.com,6.915017e+09,Female,2022-07-17,Mumbai,Maharashtra,391033.0
3,CUST000004,Girraj Mandal,girraj.mandal900@outlook.com,8.332893e+09,Male,2024-01-12,Margao,Goa,793662.0
4,CUST000005,Tanmay Das,tanmay.das242@yahoo.com,8.688820e+09,Male,2022-07-04,Hyderabad,Telangana,316263.0

In [21]:
df.sample(10)

,customer_id,customer_name,email,phone,gender,signup_date,city,state,pincode
36527,CUST036528,Heena Bhatia,heena.bhatia790@gmail.com,8.299003e+09,Female,2023-03-28,Visakhapatnam,Andhra Pradesh,201669.0
645,CUST000646,Kishore Ganguly,kishore.ganguly33@gmail.com,8.413482e+09,Male,2023-08-07,Gurugram,Haryana,558613.0
10003,CUST010004,Ishaan Karmakar,ishaan.karmakar830@outlook.com,7.513902e+09,Male,2022-10-02,Ajmer,Rajasthan,161911.0
5602,CUST005603,Anjali Pal,anjali.pal82@yahoo.com,9.991561e+09,Female,2022-01-17,Vadodara,Gujarat,515758.0
18580,CUST018581,Rashmi Mandal,rashmi.mandal77@yahoo.com,NaN,Female,2022-04-20,Ranchi,Jharkhand,151858.0
21045,CUST021046,Ishaan Sharma,ishaan.sharma94@gmail.com,9.889703e+09,Male,2023-03-07,Mumbai,Maharashtra,391449.0
2848,CUST002849,Nisha Deshmukh,nisha.deshmukh685@gmail.com,9.767062e+09,Female,2022-06-13,Mumbai,Maharashtra,391715.0
11353,CUST011354,Bhavna Halder,bhavna.halder325@yahoo.com,9.314503e+09,Female,2022-11-24,Noida,Uttar Pradesh,747207.0
3319,CUST003320,Meena Bhagat,meena.bhagat341@outlook.com,7.945848e+09,Female,2024-05-04,Pune,Maharashtra,534802.0
28466,CUST028467,Jasmine Bhattacharya,jasmine.bhattacharya62@gmail.com,8.407883e+09,Other,2022-09-26,Surat,Gujarat,713053.0

In [22]:
print("Total Rows In The Dataset:",df.shape[0])
print("Total Columns In The Dataset:",df.shape[1])

Total Rows In The Dataset: 40000
Total Columns In The Dataset: 9

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    40000 non-null  object
 1   customer_name  40000 non-null  object
 2   email          39200 non-null  object
 3   phone          39201 non-null  float64
 4   gender         40000 non-null  object
 5   signup_date    40000 non-null  datetime64[ns]
 6   city           39600 non-null  object
 7   state          39600 non-null  object
 8   pincode        39840 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 2.7+ MB

In [24]:
print("Total Missing Values In Columns:")
missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)
    
result = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_pct
})
    
print(result[result["missing_count"] > 0])

Total Missing Values In Columns:
         missing_count  missing_percent
email              800              2.0
phone              799              2.0
city               400              1.0
state              400              1.0
pincode            160              0.4

In [25]:
print("Total Duplicates Rows In customer_id:",df.duplicated(subset=["customer_id"]).sum())

Total Duplicates Rows In customer_id: 0

In [26]:
df['email'] = df['email'].fillna('Unknown')
df['phone'] = df['phone'].fillna(-1)

df['city'] = df['city'].fillna('Unknown')
df['state'] = df['state'].fillna('Unknown')
df['pincode'] = df['pincode'].fillna(-1)

In [27]:
df['phone'] = df['phone'].astype('Int64')
df['pincode'] = df['pincode'].astype('Int64')

In [28]:
# String Cleaning:
df['gender'] = (df["gender"]
                .str.strip()
                .str.lower()
                .str.title()
)

df['state'] = (df["state"]
                .str.strip()
                .str.lower()
                .str.title()
)

df['city'] = (df["city"]
                .str.strip()
                .str.lower()
                .str.title()
)

city_map = {"Banglore": "Bengaluru", "Gurgaon": "Gurugram", "Baroda": "Vadodara",
              "Calcutta": "Kolkata", "Allahabad": "Prayagraj"}
df['city'] = df['city'].replace(city_map)

In [29]:
df["gender"].value_counts()

gender
Male      20279
Female    18897
Other       824
Name: count, dtype: int64

In [30]:
print("Total State:", df["state"].nunique(),"\n")
print(df["state"].value_counts())

Total State: 29

state
Uttar Pradesh        5464
Maharashtra          5414
Karnataka            3112
Gujarat              3105
Tamil Nadu           2989
Delhi                2503
Rajasthan            1960
Telangana            1949
Haryana              1833
Madhya Pradesh       1697
West Bengal          1602
Kerala               1424
Punjab               1146
Andhra Pradesh       1122
Odisha                682
Jharkhand             632
Bihar                 619
Chandigarh            510
Unknown               400
Assam                 371
Uttarakhand           300
Chhattisgarh          293
Goa                   217
Jammu And Kashmir     189
Himachal Pradesh      134
Puducherry            115
Meghalaya              85
Nagaland               73
Manipur                60
Name: count, dtype: int64

In [31]:
print("Total City:", df["city"].nunique(),"\n")
print(df["city"].value_counts())

Total City: 84

city
Delhi        2500
Mumbai       2451
Bengaluru    2333
Hyderabad    1794
Chennai      1714
             ...
Belagavi      114
Margao         91
Shillong       85
Dimapur        74
Imphal         59
Name: count, Length: 84, dtype: int64

In [32]:
# Detect near-duplicate customers (similar name + phone) with different customer_id
dupe_phone = df[df.duplicated(subset=['phone'], keep=False) & (df['phone'] != -1)]
print("Customers sharing phone numbers:", dupe_phone.shape[0])
dupe_phone

Customers sharing phone numbers: 8

,customer_id,customer_name,email,phone,gender,signup_date,city,state,pincode
389,CUST000390,Hina Trivedi,amit.sethi31@gmail.com,8956364866,Male,2022-05-25,Kota,Rajasthan,568315
2121,CUST002122,Balaji Bajwa,balaji.bajwa740@gmail.com,6778829499,Male,2023-02-28,Visakhapatnam,Andhra Pradesh,201313
3623,CUST003624,Ritu Bhagat,qasim.ahluwalia882@outlook.com,6761407555,Male,2023-02-16,Mumbai,Maharashtra,391883
5191,CUST005192,Javed Solanki,rakesh.chandel479@outlook.com,6915339144,Male,2024-01-10,Gwalior,Madhya Pradesh,231751
8892,CUST008893,Balaji Bajwa,zoya.gaikwad334@gmail.com,6778829499,Other,2024-04-11,Chennai,Tamil Nadu,536121
24118,CUST024119,Javed Solanki,javed.solanki51@gmail.com,6915339144,Male,2022-09-25,Delhi,Delhi,336717
36745,CUST036746,Ritu Bhagat,ritu.bhagat261@outlook.com,6761407555,Female,2023-01-24,Ahmedabad,Gujarat,223457
38799,CUST038800,Hina Trivedi,hina.trivedi216@gmail.com,8956364866,Female,2023-05-18,Mumbai,Maharashtra,391404

In [33]:
df.sample(10)

,customer_id,customer_name,email,phone,gender,signup_date,city,state,pincode
1083,CUST001084,Madhavi Thakur,madhavi.thakur543@outlook.com,6668084378,Female,2023-07-15,Kota,Rajasthan,568525
39699,CUST039700,Rajat Mishra,rajat.mishra947@outlook.com,9222669544,Male,2022-04-08,Bhopal,Madhya Pradesh,753288
12674,CUST012675,Ekta Bansal,ekta.bansal621@outlook.com,6123844511,Female,2025-01-09,Indore,Madhya Pradesh,575907
20288,CUST020289,Sakshi Kumar,sakshi.kumar223@yahoo.com,6294196971,Female,2023-11-16,Delhi,Delhi,336569
9406,CUST009407,Vihaan Gill,vihaan.gill185@gmail.com,9187803537,Male,2025-03-08,Lucknow,Uttar Pradesh,753149
14907,CUST014908,Naresh Kapoor,naresh.kapoor95@outlook.com,9297713327,Other,2024-04-18,Pune,Maharashtra,534599
25133,CUST025134,Radhika Raina,radhika.raina747@outlook.com,8374992650,Female,2023-07-19,Pune,Maharashtra,534365
37136,CUST037137,Nandini Trivedi,nandini.trivedi433@gmail.com,9995734808,Female,2022-06-02,Patna,Bihar,798092
16280,CUST016281,Ekta Iyer,ekta.iyer32@outlook.com,8796609299,Female,2024-07-01,Pune,Maharashtra,534348
25295,CUST025296,Rajat Verma,rajat.verma401@yahoo.com,6834946271,Male,2024-12-16,Chandigarh,Chandigarh,441582

In [34]:
df.to_csv("../Clean Data/customers.csv",index=False)

In [35]:
print(f"Memory Usage: {df.memory_usage(deep=True).sum()/1024**2:.2f} MB")
print(df.dtypes)

Memory Usage: 16.69 MB
customer_id              object
customer_name            object
email                    object
phone                     Int64
gender                   object
signup_date      datetime64[ns]
city                     object
state                    object
pincode                   Int64
dtype: object