In [1]:
import pandas as pd

In [2]:
# =====================================================
# Load Dataset & Basic Preprocessing
# =====================================================

df = pd.read_csv("../Raw Data/sellers.csv")
df['seller_signup_date'] = pd.to_datetime(df['seller_signup_date'])
df.head()

,seller_id,seller_name,seller_city,seller_state,seller_signup_date,primary_category,seller_rating,seller_tier
0,SELR000001,Banerjee Bella Traders,Vadodara,Gujarat,2024-02-08,Beauty & Personal Care,2.9,Low
1,SELR000002,Radiance Impex,Mysuru,Karnataka,2023-12-11,Beauty & Personal Care,3.8,Medium
2,SELR000003,Sharma Junction,Vijayawada,Andhra Pradesh,2022-09-30,Grocery,2.9,Low
3,SELR000004,Tiwari Traders,Prayagraj,Uttar Pradesh,2022-11-22,Sports & Fitness,4.0,Medium
4,SELR000005,Yadav Traders,Ranchi,Jharkhand,2024-05-18,Electronics,NaN,High

In [3]:
df.sample(10)

,seller_id,seller_name,seller_city,seller_state,seller_signup_date,primary_category,seller_rating,seller_tier
894,SELR000895,Bhan Emporium,Surat,Gujarat,2024-02-11,Toys & Baby Products,3.4,Low
969,SELR000970,Sharma Global,Jaipur,Rajasthan,2025-07-24,Home & Kitchen,4.3,Medium
484,SELR000485,Thakur Marketing,Indore,Madhya Pradesh,2023-11-08,Electronics,4.4,High
212,SELR000213,Zutshi Harvest Traders,Surat,Gujarat,2023-04-06,Grocery,4.3,Medium
1129,SELR001130,Pandey Marketing,Lucknow,Uttar Pradesh,2023-11-21,Home & Kitchen,3.4,Low
800,SELR000801,Ghosh Fresh Electricals,Bhubaneswar,Odisha,2025-04-05,Grocery,3.6,Low
219,SELR000220,Grover Trading Co,Warangal,Telangana,2024-05-24,Toys & Baby Products,4.4,Medium
1163,SELR001164,Ahluwalia Global,Hyderabad,Telangana,2024-05-26,Toys & Baby Products,4.5,Medium
196,SELR000197,Agarwal Glow Solutions,Mumbai,Maharashtra,2022-08-04,Beauty & Personal Care,4.4,Medium
132,SELR000133,Bloom Industries,Nashik,Maharashtra,2023-06-26,Beauty & Personal Care,4.5,Medium

In [4]:
print("Total Rows In The Dataset:",df.shape[0])
print("Total Columns In The Dataset:",df.shape[1])

Total Rows In The Dataset: 1200
Total Columns In The Dataset: 8

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   seller_id           1200 non-null   object
 1   seller_name         1200 non-null   object
 2   seller_city         1200 non-null   object
 3   seller_state        1200 non-null   object
 4   seller_signup_date  1200 non-null   datetime64[ns]
 5   primary_category    1200 non-null   object
 6   seller_rating       1188 non-null   float64
 7   seller_tier         1200 non-null   object
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 75.1+ KB

In [6]:
df.describe()

        seller_signup_date  seller_rating
count                 1200    1188.000000
mean   2024-01-15 04:50:24       3.926431
min    2022-07-10 00:00:00       1.900000
25%    2023-03-31 18:00:00       3.600000
50%    2023-12-27 00:00:00       4.000000
75%    2024-10-29 06:00:00       4.300000
max    2025-08-22 00:00:00       5.000000
std                    NaN       0.520814

In [7]:
print("Total Missing Values In Columns:")
missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)
    
result = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_pct
})
    
print(result[result["missing_count"] > 0])

Total Missing Values In Columns:
               missing_count  missing_percent
seller_rating             12              1.0

In [8]:
print("Total Duplicates Rows In seller_id:",df.duplicated(subset=["seller_id"]).sum())

Total Duplicates Rows In seller_id: 0

In [9]:
df['seller_rating'] = df['seller_rating'].fillna(
    df.groupby('seller_tier')['seller_rating'].transform('median')
)

In [10]:
# String Cleaning:
df['seller_name'] = (df["seller_name"]
                .str.strip()
                .str.lower()
                .str.title()
)

df['seller_state'] = (df["seller_state"]
                .str.strip()
                .str.lower()
                .str.title()
)

df['seller_city'] = (df["seller_city"]
                .str.strip()
                .str.lower()
                .str.title()
)

df['primary_category'] = (df["primary_category"]
                .str.strip()
                .str.lower()
                .str.title()
)

In [11]:
print("Total State:", df["seller_state"].nunique(),"\n")
print(df["seller_state"].value_counts())

Total State: 27

seller_state
Maharashtra          165
Uttar Pradesh        150
Gujarat              111
Tamil Nadu            96
Karnataka             83
Delhi                 79
Madhya Pradesh        63
Rajasthan             62
Telangana             53
Haryana               49
Andhra Pradesh        39
West Bengal           39
Kerala                39
Punjab                34
Odisha                29
Jharkhand             24
Bihar                 16
Chhattisgarh          13
Chandigarh            11
Goa                    9
Uttarakhand            8
Assam                  7
Jammu And Kashmir      7
Puducherry             6
Himachal Pradesh       4
Manipur                3
Nagaland               1
Name: count, dtype: int64

In [12]:
print("Total City:", df["seller_city"].nunique(),"\n")
print(df["seller_city"].value_counts())

Total City: 82

seller_city
Mumbai        81
Delhi         79
Bengaluru     61
Chennai       51
Hyderabad     49
              ..
Kota           2
Aurangabad     2
Dimapur        1
Rohtak         1
Kollam         1
Name: count, Length: 82, dtype: int64

In [13]:
print("Total Category:", df["primary_category"].nunique(),"\n")
print(df["primary_category"].value_counts())

Total Category: 8

primary_category
Fashion                   273
Home & Kitchen            208
Electronics               168
Toys & Baby Products      151
Beauty & Personal Care    141
Grocery                    97
Books                      83
Sports & Fitness           79
Name: count, dtype: int64

In [14]:
df.sample(10)

,seller_id,seller_name,seller_city,seller_state,seller_signup_date,primary_category,seller_rating,seller_tier
734,SELR000735,Jadhav Traders,Varanasi,Uttar Pradesh,2023-04-03,Sports & Fitness,4.7,High
823,SELR000824,Weave Collection,Ludhiana,Punjab,2024-11-20,Fashion,4.1,Medium
1110,SELR001111,Gill Emporium,Patiala,Punjab,2022-12-15,Toys & Baby Products,3.5,Medium
879,SELR000880,Ahluwalia Emporium,Mumbai,Maharashtra,2024-04-25,Electronics,3.9,Medium
428,SELR000429,Rawat Style Textiles,Ranchi,Jharkhand,2025-05-04,Fashion,4.5,High
759,SELR000760,Jadhav Glow Collection,Ahmedabad,Gujarat,2023-12-19,Beauty & Personal Care,3.7,Medium
31,SELR000032,Sisodia Traders,Varanasi,Uttar Pradesh,2022-09-14,Beauty & Personal Care,2.9,Low
1158,SELR001159,Biswas Wholesale,Faridabad,Haryana,2022-07-25,Toys & Baby Products,3.5,Medium
487,SELR000488,Pillai Solutions,Tiruchirappalli,Tamil Nadu,2024-12-28,Home & Kitchen,4.3,Medium
1140,SELR001141,Trend Bazaar,Ajmer,Rajasthan,2023-06-10,Fashion,3.9,Medium

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   seller_id           1200 non-null   object
 1   seller_name         1200 non-null   object
 2   seller_city         1200 non-null   object
 3   seller_state        1200 non-null   object
 4   seller_signup_date  1200 non-null   datetime64[ns]
 5   primary_category    1200 non-null   object
 6   seller_rating       1200 non-null   float64
 7   seller_tier         1200 non-null   object
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 75.1+ KB

In [16]:
df.to_csv("../Clean Data/sellers.csv",index=False)

In [17]:
print(f"Memory Usage: {df.memory_usage(deep=True).sum()/1024**2:.2f} MB")
print(df.dtypes)

Memory Usage: 0.48 MB
seller_id                     object
seller_name                   object
seller_city                   object
seller_state                  object
seller_signup_date    datetime64[ns]
primary_category              object
seller_rating                float64
seller_tier                   object
dtype: object