In [1]:
import pandas as pd

In [2]:
# =====================================================
# Load Dataset & Basic Preprocessing
# =====================================================

df = pd.read_csv("../Raw Data/payment.csv")
df['payment_date'] = pd.to_datetime(df['payment_date'])
df.head()

,payment_id,order_id,payment_method,payment_status,payment_amount,payment_date
0,PYMT000001,ORDR000001,COD,Success,8015.37,2024-01-06
1,PYMT000002,ORDR000002,UPI,Success,1214.09,2024-01-01
2,PYMT000003,ORDR000003,UPI,Failed,0.00,NaT
3,PYMT000004,ORDR000004,Credit Card,Success,38798.03,2024-01-01
4,PYMT000005,ORDR000005,UPI,Refunded,16971.77,2024-01-01

In [3]:
df.sample(10)

,payment_id,order_id,payment_method,payment_status,payment_amount,payment_date
4088,PYMT004089,ORDR004089,UPI,Success,33652.84,2024-02-14
87754,PYMT087755,ORDR087755,UPI,Success,2157.83,2025-10-21
89641,PYMT089642,ORDR089642,Wallet,Success,591.39,2025-10-24
63482,PYMT063483,ORDR063483,Debit Card,Success,619.80,2025-06-08
49565,PYMT049566,ORDR049566,UPI,Success,2615.87,2025-02-27
27899,PYMT027900,ORDR027900,Credit Card,Success,506.49,2024-10-04
90831,PYMT090832,ORDR090832,COD,Success,1912.66,2025-11-03
81202,PYMT081203,ORDR081203,Credit Card,Success,235.62,2025-10-01
62234,PYMT062235,ORDR062235,Debit Card,Success,107.95,2025-06-01
76653,PYMT076654,ORDR076654,Credit Card,Success,4180.29,2025-09-05

In [4]:
print("Total Rows In The Dataset:",df.shape[0])
print("Total Columns In The Dataset:",df.shape[1])

Total Rows In The Dataset: 103748
Total Columns In The Dataset: 6

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103748 entries, 0 to 103747
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   payment_id      103748 non-null  object
 1   order_id        103748 non-null  object
 2   payment_method  103748 non-null  object
 3   payment_status  103748 non-null  object
 4   payment_amount  103748 non-null  float64
 5   payment_date    95483 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 4.7+ MB

In [6]:
df.describe()

       payment_amount                   payment_date
count   103748.000000                          95483
mean     10327.752651  2025-02-24 15:24:33.246546944
min          0.000000            2024-01-01 00:00:00
25%        944.332500            2024-09-21 00:00:00
50%       3395.635000            2025-03-15 00:00:00
75%      10930.620000            2025-09-10 00:00:00
max     374193.750000            2025-12-31 00:00:00
std      19905.227928                            NaN

In [7]:
# String Cleaning:
df['payment_method'] = (df["payment_method"]
                .str.strip()
                .str.lower()
                .str.title()
)

df['payment_status'] = (df["payment_status"]
                .str.strip()
                .str.lower()
                .str.title()
)
df['payment_method'] = df['payment_method'].replace({'Upi': 'UPI', 'Cod': 'COD'})

In [8]:
print("Total Missing Values In Columns:")
missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)
    
result = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_pct
})
    
print(result[result["missing_count"] > 0])

Total Missing Values In Columns:
              missing_count  missing_percent
payment_date           8265             7.97

In [9]:
print("Total Duplicates Rows In payment_id:",df.duplicated(subset=["payment_id"]).sum())
print("Total Duplicates Rows In order_id:",df.duplicated(subset=["order_id"]).sum())

Total Duplicates Rows In payment_id: 0
Total Duplicates Rows In order_id: 0

In [10]:
print("Total payment_method:", df["payment_method"].nunique(),"\n")
print(df["payment_method"].value_counts())

Total payment_method: 6

payment_method
UPI            41346
COD            24623
Credit Card    15315
Debit Card     10949
Net Banking     6067
Wallet          5448
Name: count, dtype: int64

In [11]:
print("Payment Status:", df["payment_status"].nunique(),"\n")
print(df["payment_status"].value_counts())

Payment Status: 4

payment_status
Success     92705
Pending      4269
Failed       3611
Refunded     3163
Name: count, dtype: int64

In [12]:
df.to_csv("../Clean Data/payment.csv",index=False)

In [13]:
print(f"Memory Usage: {df.memory_usage(deep=True).sum()/1024**2:.2f} MB")
print(df.dtypes)

Memory Usage: 27.36 MB
payment_id                object
order_id                  object
payment_method            object
payment_status            object
payment_amount           float64
payment_date      datetime64[ns]
dtype: object