In [1]:
import pandas as pd

In [2]:
# =====================================================
# Load Dataset & Basic Preprocessing
# =====================================================

df = pd.read_csv("../Raw Data/return.csv")
df['return_date'] = pd.to_datetime(df['return_date'])
df.head()

,return_id,order_id,order_item_id,return_date,return_reason,return_status,refund_amount
0,RTRN000001,ORDR000034,NaN,2024-01-13,Size issue,Rejected,4564.02
1,RTRN000002,ORDR000036,NaN,2024-01-04,Product not as described,Refunded,9383.75
2,RTRN000003,ORDR000074,NaN,2024-01-10,Size issue,Refunded,877.66
3,RTRN000004,ORDR000092,NaN,2024-01-21,Damaged product,Refunded,11647.35
4,RTRN000005,ORDR000114,NaN,2024-01-23,Damaged product,Rejected,10749.67

In [3]:
df.sample(10)

,return_id,order_id,order_item_id,return_date,return_reason,return_status,refund_amount
1605,RTRN001606,ORDR024822,NaN,2024-09-25,Product not as described,Refunded,3267.68
1540,RTRN001541,ORDR023569,NaN,2024-09-18,Late delivery,Refunded,49996.11
6776,RTRN006777,ORDR050009,OITM096701,2025-03-18,Quality issue,Refunded,2476.72
6733,RTRN006734,ORDR079852,OITM154697,2025-10-20,Wrong product,Refunded,8293.13
782,RTRN000783,ORDR011884,NaN,2024-05-28,Quality issue,Refunded,4117.66
2121,RTRN002122,ORDR032976,NaN,2024-11-15,Quality issue,Refunded,17354.00
4044,RTRN004045,ORDR062517,NaN,2025-06-19,Product not as described,Refunded,5472.15
6827,RTRN006828,ORDR076784,OITM148695,2025-09-20,Damaged product,Refunded,2843.65
549,RTRN000550,ORDR008612,NaN,2024-04-23,Late delivery,Refunded,3526.70
630,RTRN000631,ORDR009886,NaN,2024-05-03,Late delivery,Refunded,35898.80

In [4]:
print("Total Rows In The Dataset:",df.shape[0])
print("Total Columns In The Dataset:",df.shape[1])

Total Rows In The Dataset: 7020
Total Columns In The Dataset: 7

In [5]:
df.rename(columns={'refund_amount': 'return_claim_amount'}, inplace=True)
df['actual_refund'] = df.apply(
    lambda x: x['return_claim_amount'] if x['return_status'] == 'Refunded' else 0, 
    axis=1
)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7020 entries, 0 to 7019
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   return_id            7020 non-null   object
 1   order_id             7020 non-null   object
 2   order_item_id        400 non-null    object
 3   return_date          7020 non-null   datetime64[ns]
 4   return_reason        7020 non-null   object
 5   return_status        7020 non-null   object
 6   return_claim_amount  7020 non-null   float64
 7   actual_refund        7020 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 438.9+ KB

In [7]:
df.describe()

                         return_date  return_claim_amount  actual_refund
count                           7020          7020.000000    7020.000000
mean   2025-03-06 00:38:21.538461696         10480.651641    7597.896117
min              2024-01-04 00:00:00            27.460000       0.000000
25%              2024-10-04 00:00:00          1058.962500       0.000000
50%              2025-03-27 00:00:00          3455.550000    1449.575000
75%              2025-09-12 00:00:00         11106.257500    6815.715000
max              2025-12-31 00:00:00        292310.280000  284541.550000
std                              NaN         19921.187372   17511.316087

In [8]:
print("Total Missing Values In Columns:")
missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)
    
result = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_pct
})
    
print(result[result["missing_count"] > 0])

Total Missing Values In Columns:
               missing_count  missing_percent
order_item_id           6620             94.3

In [9]:
print("Total Duplicates Rows In return_id:",df.duplicated(subset=["return_id"]).sum())
print("Total Duplicates Rows In order_id:",df.duplicated(subset=["order_id"]).sum())

Total Duplicates Rows In return_id: 0
Total Duplicates Rows In order_id: 0

In [10]:
print("Return Status:", df["return_status"].nunique(),"\n")
print(df["return_status"].value_counts())

Return Status: 5

return_status
Refunded     5147
Rejected     1743
Approved       47
Picked Up      42
Requested      41
Name: count, dtype: int64

In [11]:
df.sample(10)

,return_id,order_id,order_item_id,return_date,return_reason,return_status,return_claim_amount,actual_refund
2477,RTRN002478,ORDR038067,NaN,2024-12-11,Wrong product,Rejected,9667.37,0.00
4638,RTRN004639,ORDR070843,NaN,2025-08-06,Wrong product,Refunded,1022.03,1022.03
6017,RTRN006018,ORDR091205,NaN,2025-11-10,Quality issue,Refunded,16438.17,16438.17
1913,RTRN001914,ORDR029827,NaN,2024-11-12,Product not as described,Refunded,22764.91,22764.91
1516,RTRN001517,ORDR023077,NaN,2024-09-01,Customer changed mind,Refunded,12774.66,12774.66
6895,RTRN006896,ORDR091904,OITM178305,2025-11-21,Customer changed mind,Rejected,1633.32,0.00
2847,RTRN002848,ORDR043945,NaN,2025-01-30,Size issue,Refunded,1993.12,1993.12
2307,RTRN002308,ORDR035418,NaN,2024-11-18,Customer changed mind,Refunded,710.29,710.29
460,RTRN000461,ORDR007122,NaN,2024-04-15,Product not as described,Refunded,1151.17,1151.17
1482,RTRN001483,ORDR022603,NaN,2024-09-08,Quality issue,Refunded,2162.00,2162.00

In [ ]:
df.to_csv("../Clean Data/returns.csv",index=False)

In [13]:
print(f"Memory Usage: {df.memory_usage(deep=True).sum()/1024**2:.2f} MB")
print(df.dtypes)

Memory Usage: 2.21 MB
return_id                      object
order_id                       object
order_item_id                  object
return_date            datetime64[ns]
return_reason                  object
return_status                  object
return_claim_amount           float64
actual_refund                 float64
dtype: object