In [1]:
import pandas as pd

In [2]:
# =====================================================
# Load Dataset & Basic Preprocessing
# =====================================================

df = pd.read_csv("../Raw Data/orders.csv")
df['order_date'] = pd.to_datetime(df['order_date'])
df['shipped_date'] = pd.to_datetime(df['shipped_date'])
df['delivery_date'] = pd.to_datetime(df['delivery_date'])
df['expected_delivery_date'] = pd.to_datetime(df['expected_delivery_date'])

df.head()

,order_id,customer_id,order_date,order_status,cancellation_reason,shipped_date,delivery_date,expected_delivery_date,delivery_city,delivery_state,order_total
0,ORDR000001,CUST018345,2024-01-01,Delivered,NaN,2024-01-02,2024-01-06,2024-01-07,Kollam,Kerala,8015.37
1,ORDR000002,CUST000265,2024-01-01,Delivered,NaN,2024-01-03,2024-01-05,2024-01-04,Bengaluru,Karnataka,1214.09
2,ORDR000003,CUST038247,2024-01-01,Cancelled,Customer changed mind,NaT,NaT,NaT,Varanasi,Uttar Pradesh,8236.25
3,ORDR000004,CUST031405,2024-01-01,Delivered,NaN,2024-01-03,2024-01-07,2024-01-06,Mumbai,Maharashtra,38798.03
4,ORDR000005,CUST034854,2024-01-01,Cancelled,Address issue,NaT,NaT,NaT,Bengaluru,Karnataka,16971.77

In [3]:
df.sample(10)

,order_id,customer_id,order_date,order_status,cancellation_reason,shipped_date,delivery_date,expected_delivery_date,delivery_city,delivery_state,order_total
42331,ORDR042332,CUST027019,2024-12-31,Delivered,NaN,2025-01-01,2025-01-05,2025-01-05,Surat,Gujarat,5044.88
23681,ORDR023682,CUST032620,2024-08-30,Delivered,NaN,2024-09-01,2024-09-03,2024-09-03,Hyderabad,Telangana,3765.68
68707,ORDR068708,CUST002896,2025-07-16,Delivered,NaN,2025-07-18,2025-07-21,2025-07-20,Faridabad,Haryana,2843.67
33301,ORDR033302,CUST014459,2024-11-01,Delivered,NaN,2024-11-01,2024-11-06,2024-11-08,Moradabad,Uttar Pradesh,2043.94
7404,ORDR007405,CUST027159,2024-03-19,Cancelled,Pricing issue,NaT,NaT,NaT,Rajkot,Gujarat,10363.89
81562,ORDR081563,CUST018417,2025-10-03,Delivered,NaN,2025-10-03,2025-10-08,2025-10-07,Bengaluru,Karnataka,3264.70
97609,ORDR097610,CUST009718,2025-11-28,Delivered,NaN,2025-11-29,2025-11-30,2025-12-01,Noida,Uttar Pradesh,19827.94
18384,ORDR018385,CUST039735,2024-07-11,Returned,NaN,2024-07-13,2024-07-16,2024-07-17,Indore,Madhya Pradesh,2144.97
6764,ORDR006765,CUST020176,2024-03-12,Shipped,NaN,2024-03-13,NaT,2024-03-18,Bhubaneswar,Odisha,72551.04
102249,ORDR102250,CUST007539,2025-12-25,Shipped,NaN,2025-12-25,NaT,2025-12-29,Noida,Uttar Pradesh,4385.28

In [4]:
print("Total Rows In The Dataset:",df.shape[0])
print("Total Columns In The Dataset:",df.shape[1])

Total Rows In The Dataset: 103748
Total Columns In The Dataset: 11

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103748 entries, 0 to 103747
Data columns (total 11 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_id                103748 non-null  object
 1   customer_id             103748 non-null  object
 2   order_date              103748 non-null  datetime64[ns]
 3   order_status            103748 non-null  object
 4   cancellation_reason     7599 non-null    object
 5   shipped_date            92138 non-null   datetime64[ns]
 6   delivery_date           87735 non-null   datetime64[ns]
 7   expected_delivery_date  96149 non-null   datetime64[ns]
 8   delivery_city           103748 non-null  object
 9   delivery_state          103748 non-null  object
 10  order_total             103748 non-null  float64
dtypes: datetime64[ns](4), float64(1), object(6)
memory usage: 8.7+ MB

In [6]:
print("Total Missing Values In Columns:")
missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)
    
result = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_pct
})
    
print(result[result["missing_count"] > 0])

Total Missing Values In Columns:
                        missing_count  missing_percent
cancellation_reason             96149            92.68
shipped_date                    11610            11.19
delivery_date                   16013            15.43
expected_delivery_date           7599             7.32

In [7]:
df.describe()

,order_date,shipped_date,delivery_date,expected_delivery_date,order_total
count,103748,92138,87735,96149,103748.000000
mean,2025-02-25 22:35:55.808304640,2025-02-24 14:42:54.833402112,2025-02-24 22:49:02.779962624,2025-03-03 13:30:19.937804544,10699.031283
min,2024-01-01 00:00:00,2024-01-01 00:00:00,2024-01-02 00:00:00,2024-01-04 00:00:00,21.210000
25%,2024-09-21 00:00:00,2024-09-20 06:00:00,2024-09-22 00:00:00,2024-09-27 00:00:00,1102.650000
50%,2025-03-16 00:00:00,2025-03-15 00:00:00,2025-03-15 00:00:00,2025-03-22 00:00:00,3628.780000
75%,2025-09-13 00:00:00,2025-09-10 00:00:00,2025-09-07 00:00:00,2025-09-19 00:00:00,11411.170000
max,2025-12-31 00:00:00,2026-01-02 00:00:00,2025-12-31 00:00:00,2026-01-08 00:00:00,374193.750000
std,NaN,NaN,NaN,NaN,20148.913850

In [8]:
# String Cleaning:
df['order_status'] = (df["order_status"]
                .str.strip()
                .str.lower()
                .str.title()
)

df['cancellation_reason'] = (df["cancellation_reason"]
                .str.strip()
                .str.lower()
                .str.title()
)

df['delivery_city'] = (df["delivery_city"]
                .str.strip()
                .str.lower()
                .str.title()
)

df['delivery_state'] = (df["delivery_state"]
                .str.strip()
                .str.lower()
                .str.title()
)

In [9]:
print("Total Duplicates Rows In order_id:",df.duplicated(subset=["order_id"]).sum())

Total Duplicates Rows In order_id: 0

In [10]:
print("Total State:", df["delivery_state"].nunique(),"\n")
print(df["delivery_state"].value_counts())

Total State: 28

delivery_state
Maharashtra          14278
Uttar Pradesh        14278
Karnataka             8202
Gujarat               8166
Tamil Nadu            7659
Delhi                 6693
Rajasthan             5050
Telangana             4957
Haryana               4707
Madhya Pradesh        4518
West Bengal           4231
Kerala                3700
Andhra Pradesh        3136
Punjab                2805
Odisha                1841
Bihar                 1753
Jharkhand             1625
Chandigarh            1354
Assam                 1007
Uttarakhand            781
Chhattisgarh           755
Goa                    570
Jammu And Kashmir      452
Himachal Pradesh       359
Puducherry             281
Meghalaya              245
Nagaland               199
Manipur                146
Name: count, dtype: int64

In [11]:
print("Total City:", df["delivery_city"].nunique(),"\n")
print(df["delivery_city"].value_counts())

Total City: 83

delivery_city
Delhi        6693
Mumbai       6488
Bengaluru    6112
Hyderabad    4588
Chennai      4430
             ...
Panipat       266
Shillong      245
Margao        243
Dimapur       199
Imphal        146
Name: count, Length: 83, dtype: int64

In [12]:
print("Order Status:", df["order_status"].nunique(),"\n")
print(df["order_status"].value_counts())

Order Status: 5

order_status
Delivered    81115
Cancelled     7599
Returned      6620
Shipped       4403
Pending       4011
Name: count, dtype: int64

In [13]:
# Delivery performance metrics
df['delivery_days'] = (df['delivery_date'] - df['shipped_date']).dt.days
df['delivery_delay'] = (df['delivery_date'] - df['expected_delivery_date']).dt.days

In [14]:
customer_orders = df.groupby('customer_id').agg(
    total_orders=('order_id', 'count'),
    total_spend=('order_total', 'sum'),
    last_order_date=('order_date', 'max')
).reset_index()

def segment(row):
    if row['total_orders'] == 1:
        return 'New'
    elif row['total_spend'] >= customer_orders['total_spend'].quantile(0.99):
        return 'VIP'
    else:
        return 'Repeat'

customer_orders['customer_segment'] = customer_orders.apply(segment, axis=1)

# merge back to orders df
df = df.merge(customer_orders[['customer_id', 'customer_segment']], on='customer_id', how='left')
customer_orders['customer_segment'].value_counts()

customer_segment
New       24128
Repeat    15491
VIP         381
Name: count, dtype: int64

In [15]:
df.sample(10)

,order_id,customer_id,order_date,order_status,cancellation_reason,shipped_date,delivery_date,expected_delivery_date,delivery_city,delivery_state,order_total,delivery_days,delivery_delay,customer_segment
25062,ORDR025063,CUST003208,2024-09-13,Delivered,NaN,2024-09-13,2024-09-22,2024-09-21,Jalandhar,Punjab,6005.70,9.0,1.0,Repeat
12901,ORDR012902,CUST029196,2024-05-20,Delivered,NaN,2024-05-22,2024-05-23,2024-05-24,Varanasi,Uttar Pradesh,22949.56,1.0,-1.0,Repeat
88877,ORDR088878,CUST023591,2025-10-22,Cancelled,Customer Changed Mind,NaT,NaT,NaT,Pune,Maharashtra,2269.59,NaN,NaN,Repeat
52059,ORDR052060,CUST000076,2025-03-18,Delivered,NaN,2025-03-18,2025-03-23,2025-03-24,Indore,Madhya Pradesh,321.11,5.0,-1.0,Repeat
93139,ORDR093140,CUST021297,2025-11-06,Delivered,NaN,2025-11-06,2025-11-11,2025-11-11,Gurugram,Haryana,42366.27,5.0,0.0,Repeat
10168,ORDR010169,CUST011199,2024-04-20,Delivered,NaN,2024-04-21,2024-04-23,2024-04-23,Hyderabad,Telangana,12526.93,2.0,0.0,Repeat
40692,ORDR040693,CUST019278,2024-12-21,Delivered,NaN,2024-12-22,2024-12-27,2024-12-26,Surat,Gujarat,47466.67,5.0,1.0,Repeat
65718,ORDR065719,CUST013643,2025-06-25,Delivered,NaN,2025-06-25,2025-07-01,2025-07-01,Aurangabad,Maharashtra,6473.80,6.0,0.0,Repeat
57541,ORDR057542,CUST037036,2025-05-01,Delivered,NaN,2025-05-01,2025-05-04,2025-05-06,Kolkata,West Bengal,12768.45,3.0,-2.0,Repeat
20240,ORDR020241,CUST028686,2024-07-31,Delivered,NaN,2024-08-02,2024-08-13,2024-08-05,Kochi,Kerala,409.94,11.0,8.0,Repeat

In [16]:
df.to_csv("../Clean Data/orders.csv",index=False)

In [17]:
print(f"Memory Usage: {df.memory_usage(deep=True).sum()/1024**2:.2f} MB")
print(df.dtypes)

Memory Usage: 47.87 MB
order_id                          object
customer_id                       object
order_date                datetime64[ns]
order_status                      object
cancellation_reason               object
shipped_date              datetime64[ns]
delivery_date             datetime64[ns]
expected_delivery_date    datetime64[ns]
delivery_city                     object
delivery_state                    object
order_total                      float64
delivery_days                    float64
delivery_delay                   float64
customer_segment                  object
dtype: object