In [1]:
import pandas as pd

In [2]:
# =====================================================
# Load Dataset & Basic Preprocessing
# =====================================================

df = pd.read_csv("../Raw Data/order_items.csv")
df.head(10)

,order_item_id,order_id,product_id,seller_id,quantity,unit_price,discount_percent,item_total
0,OITM000001,ORDR000001,PROD003064,SELR000964,1,9715.60,17.5,8015.37
1,OITM000002,ORDR000002,PROD001146,SELR000013,2,740.30,18.0,1214.09
2,OITM000003,ORDR000003,PROD002775,SELR000813,3,2948.89,6.9,8236.25
3,OITM000004,ORDR000004,PROD002656,SELR000869,1,5482.90,25.8,4068.31
4,OITM000005,ORDR000004,PROD003068,SELR000158,1,414.91,20.5,329.85
5,OITM000006,ORDR000004,PROD002286,SELR001171,2,18415.35,6.6,34399.87
6,OITM000007,ORDR000005,PROD002084,SELR001023,1,19990.31,15.1,16971.77
7,OITM000008,ORDR000006,PROD002286,SELR001171,1,18415.35,14.2,15800.37
8,OITM000009,ORDR000007,PROD001950,SELR000855,4,4381.12,24.2,13283.56
9,OITM000010,ORDR000008,PROD003372,SELR000196,1,1482.39,7.0,1378.62

In [3]:
df.sample(10)

,order_item_id,order_id,product_id,seller_id,quantity,unit_price,discount_percent,item_total
55950,OITM055951,ORDR029014,PROD000592,SELR000343,1,13009.14,36.1,8312.84
73215,OITM073216,ORDR037918,PROD000797,SELR000376,1,1411.30,24.1,1071.18
149984,OITM149985,ORDR077467,PROD000419,SELR000136,1,1274.45,9.4,1154.65
45344,OITM045345,ORDR023564,PROD000182,SELR001005,2,5057.74,24.4,7647.30
180392,OITM180393,ORDR092938,PROD001104,SELR000121,1,1108.05,23.5,847.66
123722,OITM123723,ORDR063914,PROD002198,SELR000733,1,142.62,24.2,108.11
102885,OITM102886,ORDR053265,PROD003107,SELR000455,1,3874.85,15.6,3270.37
168902,OITM168903,ORDR087153,PROD001826,SELR000422,1,627.96,49.8,315.24
18312,OITM018313,ORDR009478,PROD001194,SELR000409,1,10361.41,16.9,8610.33
153743,OITM153744,ORDR079357,PROD000355,SELR000086,2,620.10,14.2,1064.09

In [4]:
print("Total Rows In The Dataset:",df.shape[0])
print("Total Columns In The Dataset:",df.shape[1])

Total Rows In The Dataset: 200966
Total Columns In The Dataset: 8

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200966 entries, 0 to 200965
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   order_item_id     200966 non-null  object
 1   order_id          200966 non-null  object
 2   product_id        200966 non-null  object
 3   seller_id         200966 non-null  object
 4   quantity          200966 non-null  int64
 5   unit_price        200966 non-null  float64
 6   discount_percent  200966 non-null  float64
 7   item_total        200966 non-null  float64
dtypes: float64(3), int64(1), object(4)
memory usage: 12.3+ MB

In [6]:
df.describe()

            quantity     unit_price  discount_percent     item_total
count  200966.000000  200966.000000     200966.000000  200966.000000
mean        1.396798    4935.582560         20.698642    5523.337766
std         0.809631    9430.337175         11.149529   13084.302607
min         1.000000      33.200000          0.000000      21.180000
25%         1.000000     589.680000         11.700000     563.342500
50%         1.000000    1617.940000         19.800000    1631.405000
75%         1.000000    5156.640000         28.500000    4506.900000
max         5.000000   77934.410000         55.000000  374193.750000

In [7]:
print("Total Missing Values In Columns:")
missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)
    
result = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_pct
})
    
print(result[result["missing_count"] > 0])

Total Missing Values In Columns:
Empty DataFrame
Columns: [missing_count, missing_percent]
Index: []

In [8]:
print("Total Duplicates Rows In order_id:",df.duplicated(subset=["order_item_id"]).sum())

Total Duplicates Rows In order_id: 0

In [9]:
products = pd.read_csv("../Raw Data/products.csv")[['product_id', 'cost_price']]
df = df.merge(products, on='product_id', how='left')

df['profit'] = (df['item_total'] - (df['cost_price'] * df['quantity'])).round(2)

print("Negative profit rows (loss-making sales):", (df['profit'] < 0).sum())
df.sample(10)

Negative profit rows (loss-making sales): 74231

,order_item_id,order_id,product_id,seller_id,quantity,unit_price,discount_percent,item_total,cost_price,profit
143287,OITM143288,ORDR073956,PROD001076,SELR001047,2,5051.17,38.5,6212.94,3150.47,-88.00
75835,OITM075836,ORDR039278,PROD001968,SELR000803,1,304.14,8.3,278.90,232.03,46.87
161372,OITM161373,ORDR083319,PROD001654,SELR001165,1,1022.19,28.5,730.87,820.98,-90.11
163855,OITM163856,ORDR084619,PROD000355,SELR000086,1,620.10,24.4,468.80,454.36,14.44
66052,OITM066053,ORDR034200,PROD000943,SELR000680,1,835.72,35.8,536.53,559.03,-22.50
90314,OITM090315,ORDR046606,PROD001414,SELR000633,4,10418.97,8.0,38341.81,7852.39,6932.25
69966,OITM069967,ORDR036236,PROD003335,SELR000223,2,732.54,26.6,1075.37,511.34,52.69
40880,OITM040881,ORDR021265,PROD001294,SELR000163,4,906.70,31.4,2487.98,627.00,-20.02
151937,OITM151938,ORDR078434,PROD003227,SELR000524,1,3999.01,9.6,3615.11,2650.66,964.45
67772,OITM067773,ORDR035079,PROD003254,SELR000871,1,1482.51,21.6,1162.29,1348.81,-186.52

In [10]:
loss_rows = df[df['profit'] < 0]
print("Avg discount on loss-making sales:", loss_rows['discount_percent'].mean())
print("Avg discount overall:", df['discount_percent'].mean())

Avg discount on loss-making sales: 30.293147067936577
Avg discount overall: 20.698642058855725

In [11]:
df.to_csv("../Clean Data/order_items.csv",index=False)

In [12]:
print(f"Memory Usage: {df.memory_usage(deep=True).sum()/1024**2:.2f} MB")
print(df.dtypes)

Memory Usage: 60.56 MB
order_item_id        object
order_id             object
product_id           object
seller_id            object
quantity              int64
unit_price          float64
discount_percent    float64
item_total          float64
cost_price          float64
profit              float64
dtype: object